.PHONY: test frontend-test frontend-build go-test integration-test

test: go-test frontend-test frontend-build

frontend-test:
	cd frontend && npm test

frontend-build:
	cd frontend && npm run build

go-test:
	cd services/api-gateway && GOCACHE=/tmp/go-build go test ./...
	cd services/planner-agent && GOCACHE=/tmp/go-build go test ./...
	cd services/retriever-agent && GOCACHE=/tmp/go-build go test ./...
	cd services/classifier-agent && GOCACHE=/tmp/go-build go test ./...
	cd services/responder-agent && GOCACHE=/tmp/go-build go test ./...
	cd services/aggregator-agent && GOCACHE=/tmp/go-build go test ./...
	cd shared/event-schema && GOCACHE=/tmp/go-build go test ./...

integration-test:
	cd services/api-gateway && GOCACHE=/tmp/go-build go test -tags=integration -run TestWorkflowCompletesAcrossServices -count=1
